

## Introduction

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We don't expect prior experience with Python and `numpy` but do expect some prior programming; the next section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing. Individuals with prior experience are advised to follow through for quick revision of concepts but may skip to the tasks if they wish to do so. Please make sure to run <span style="color: red;"> all cells </span> regardless.

Some of the things to be covered:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes

* `numpy`: Arrays, Array indexing, Datatypes, Array math, Broadcasting

* `matplotlib`: Plotting, Subplots, Images

* `scipy`: Images

* `pandas` : Reading and analyzing data



## Basics of Python



### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"

<class 'int'>
3


In [ ]:
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"

4
2
6
9


In [ ]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [ ]:
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment, or decrement operators, i.e. `x++` and `x--` respectively.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words (`and`, `or`) rather than symbols (`&&`, `||`, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


#### Strings

Python has great support for strings:

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists (`list`), dictionaries (`dict`), sets (`set`), and tuples (`tuple`).

#### Lists

A `list` is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

##### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.

In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


##### List Comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#dict).

##### Loops

It is easy to iterate over the keys in a `dict`:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


##### Dictionary Comprehensions

These are similar to list comprehensions, but allow you to easily construct `dict`s. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

#### Sets

A `set` is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


As usual, everything you want to know about sets can be found in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#set).

##### Loops

Iterating over a `set` has the same syntax as iterating over a `list`; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: cat", "#3: dog"

#1: dog
#2: cat
#3: fish


##### Set Comprehensions

Like lists and dicts, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


The [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#tuples-and-sequences) has more information about tuples.

### Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


There is a lot more information about Python functions in the [documentation](https://docs.python.org/3.7/tutorial/controlflow.html#defining-functions).

#### Lambda Functions
These are anonymous functions in Python which take any number of arguments but only one expression. Their syntax generally follows:

`lambda arguments : expression`.

They are one line function and expression are representing the body of a normal function.

In [ ]:
l = lambda a : a+5  ## lambda function 'l' is created which is taking 'a' as an argument and expression adds 5 to the value of argument a
print(l(2))  ## passing 2 as value of 'a' argument of lambda function 'l' . This will return 7(7 = 2+5) as output.

l1 = lambda a,b,c : a * b * c ## lambda function 'l1' is created which is taking 3 arguments (a,b,c) and return the result by multiplying them all.
print(l1(10,20,30))  ## passing 10,20,30 as arguments 'a', 'b', 'c' respectively to 'l1' function. Print result 6000 (6000 = 10*20*30)

7
6000


### Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

# Tasks

### Q1
Write code to determine whether a number is even or odd and print it.

In [ ]:
number = 5
### Code here
if number %2 == 0:
  print(number, 'is even.')
else:
  print(number, 'is odd.')

5 is odd.


### Q2

For a given list of strings, check if the length of each string is even or odd. Print `even` or `odd` accordingly.

In [ ]:
x = ['alphabets', 'numerics', 'data types', '123', 'wild' ,'abc', 'chars']

### Code here
for strings in x:
  if len(strings) %2 == 0:
    print(strings, 'is even.')
  else:
    print(strings, 'is odd.')



alphabets is odd.
numerics is even.
data types is even.
123 is odd.
wild is even.
abc is odd.
chars is odd.


### Q3

Write a code to reverse the string `hello` using indexing and print it.

In [ ]:
greeting='hello'

### Code here
### print(greeting[::-1])

for i in range (len(greeting) -1, -1, -1):
  print(greeting[i], end="")


olleh

### Q4

For numbers in range `0` to `100`, return a list of those that are multiple of `2` but not `5`

In [ ]:
def func():
    ### Code here
    l1=[]
    for i in range(101):
      if i%2 == 0 and i%5 != 0:
        l1.append(i)
    return l1

l1= func()
print('List of multiples of 2 but not 5:',)
print(l1)



List of multiples of 2 but not 5:
[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48, 52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]


### Q5

Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.

In [ ]:
str = "Hello Mr. Rogers, how are you this fine Tuesday?"

def enum_cases(string):
    ### Code here
    upper= 0
    lower= 0
    for char in str:
      if char.isupper():
        upper += 1
      elif char.islower():
        lower += 1
    return upper, lower

print('Upper case characters: %d\nLower case characters: %d'% enum_cases(str))

Upper case characters: 4
Lower case characters: 33


### Q6

Write a function that prints the integers from 1 to 100. But for multiples of three, print `Fizz` instead of the number, and for the multiples of five print `Buzz`. For numbers which are multiples of both three and five print `FizzBuzz`.

In [ ]:
def special_print():
    ### Code here
    for i in range(1, 101):
      if i%3 == 0 and i%5 == 0:
        print("FizzBuzz")

      elif i%3 == 0:
        print("Fizz")

      elif i%5 == 0:
        print("Buzz")

      else:
        print(i)

special_print()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


### Q7

Write a function, `calculateSum(l,k)` which will take a list, `l` and a number `k` as input and return two numbers from `l` that add up to `k`.

In [ ]:
l = [1, 21, 3, 14, 5, 60, 7, 6]
k = 81

### Code here
def calculateSum(l,k):
    ### Code here
    pass

print(calculateSum(l,k))


### Q8

Write a function, `find_students`  that receives the `students` dictionary and an `address`, and returns a `list` with names in sorted order of all students whose address matches the address in the argument.

In [ ]:
def find_students(address, students):
  ### Code here

  result=[]
  for name, value in students.items():
    if value["address"] == address:
      result.append(name)
  result.sort()
  return result


students = {
      "Ali": {"age": 6, "address": "Lahore"},
      "Ahmad": {"age": 15, "address": "Islamabad"},
      "Eesha": {"age": 21, "address": "Karachi"},
}
print(find_students("Lahore", students))

['Ali']


### Q9

Given an unsorted list of integers, write a function first_missing_positive that returns the smallest missing positive integer.

In [ ]:
def first_missing_positive(nums):
    ### Modify the input list in-place to track seen numbers
    i=1

    while i in nums:
      i+=1
    return i


print(first_missing_positive([3, 4, -1, 1]))  # Output: 2
print(first_missing_positive([1, 2, 0]))      # Output: 3
print(first_missing_positive([7, 8, 9, 11]))  # Output: 1

2
3
1


### Q10

Write a function flatten_dict that takes a nested dictionary and returns a flattened version where keys are concatenated with underscores for nested levels. Handle edge cases like empty dictionaries or non-dictionary values.

In [ ]:
nested_dict = {
    'a': 1,
    'b': {
        'c': 2,
        'd': {
            'e': 3,
            'f': 4
        }
    },
    'g': 5
}

def flatten_dict(d, parent_key='', sep='_'):
    ### Code here
    result ={}
    for key, value in d.items():
      new_key = parent_key + sep + key if parent_key else key

      if isinstance(value, dict):
        result.update(flatten_dict(value, new_key, sep))
      else:
        result[new_key] = value
    return result

print(flatten_dict(nested_dict))
# Expected Output: {'a': 1, 'b_c': 2, 'b_d_e': 3, 'b_d_f': 4, 'g': 5}

{'a': 1, 'b_c': 2, 'b_d_e': 3, 'b_d_f': 4, 'g': 5}


### Q11

Given a list of tuples representing student names and their scores, write a function top_student that returns the name of the student with the highest score.

In [ ]:
scores = [("Ali", 85), ("Ahmad", 92), ("Aisha", 78)]

def top_student(students):
    ### Code here
    highest= 0
    name= ""
    for student, score in scores:
      if score > highest:
        highest=score
        name=student
    return name


print(top_student(scores))  # Expected output: "Ahmad"

Ahmad


### Q12
Write a function count_vowels that takes a string and returns a dictionary where the keys are vowels (a, e, i, o, u) and the values are their respective counts in the string (case-insensitive).

In [ ]:
text = "Hello, how are you today?"

def count_vowels(s):
    ### Code here
    vowels = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
    for char in s.lower():
      if char in vowels:
        vowels[char] +=1
    return vowels

print(count_vowels(text))  # Expected output: {'a': 2, 'e': 2, 'i': 0, 'o': 3, 'u': 1}

{'a': 2, 'e': 2, 'i': 0, 'o': 4, 'u': 1}


### Q13

Given a list of numbers, write a function remove_outliers that removes the smallest and largest numbers from the list and returns the modified list.

In [ ]:
numbers = [12, 3, 45, 7, 1, 67, 9]

def remove_outliers(lst):
    ### Code here
    lst.remove(min(lst))
    lst.remove(max(lst))
    return lst
    pass

print(remove_outliers(numbers))  # Expected output: [12, 3, 45, 7, 9]

[12, 3, 45, 7, 9]


### Q14
Longest Consecutive Sequence in a List
Given an unsorted list of integers, write a function longest_consecutive_sequence that returns the length of the longest consecutive sequence of numbers (e.g., [100, 4, 200, 1, 3, 2] → 4 because 1, 2, 3, 4 is the longest sequence).

In [ ]:
nums = [100, 4, 200, 1, 3, 2, 101, 99, 102, 103, 104]

def longest_consecutive_sequence(nums):
    ### Code here
    nums.sort()
    longest = 1
    current = 1

    for i in range(1, len(nums)):
        if nums[i] == nums[i - 1] + 1:
            current+= 1
        elif nums[i] != nums[i - 1]:
            current = 1

        if current > longest:
            longest = current

    return longest
    pass

print(longest_consecutive_sequence(nums))  # Expected Output: 5 (99, 100, 101, 102, 103, 104)

6


### Q15
Implement a Trie (Prefix Tree)
Write a class Trie with methods insert(word), search(word), and startsWith(prefix) to efficiently store and retrieve words.

In [ ]:
class Trie:
    def __init__(self):
        self.root = {}

    def insert(self, word):
        current = self.root

        for char in word:
            if char not in current:
                current[char] = {}
            current = current[char]

        current["*"] = True

    def search(self, word):
        current = self.root

        for char in word:
            if char not in current:
                return False
            current = current[char]

        return "*" in current

    def startsWith(self, prefix):
        current = self.root

        for char in prefix:
            if char not in current:
                return False
            current = current[char]

        return True


trie = Trie()

trie.insert("apple")
print(trie.search("apple"))    # True
print(trie.search("app"))      # False
print(trie.startsWith("app"))  # True

trie.insert("app")
print(trie.search("app"))      # True

True
False
True
True


### Q16
Design a CircularBuffer class that supports:

append(x): Add an element to the buffer. If full, overwrite the oldest element.

get(): Return the buffer as a list in insertion order.



In [ ]:
class CircularBuffer:
    def __init__(self, size):
        self.size = size
        self.buffer = []

    def append(self, x):
        if len(self.buffer) < self.size:
            self.buffer.append(x)
        else:
            self.buffer.pop(0)
            self.buffer.append(x)

    def get(self):
        return self.buffer


cb = CircularBuffer(3)
cb.append(1)
cb.append(2)
cb.append(3)
print(cb.get())  # [1, 2, 3]
cb.append(4)
print(cb.get())  # [2, 3, 4]

[1, 2, 3]
[2, 3, 4]


### Q17
Write a function one_hot_encode that converts categorical labels (e.g., ["cat", "dog", "bird"]) into one-hot encoded arrays without using OneHotEncoder.

In [ ]:
import numpy as np
def one_hot_encode(labels):
    """
    labels: List of categorical labels (e.g., ["cat", "dog", "cat"]).
    Returns a 2D NumPy array where each row is a one-hot vector.
    """
    ### Your code here
    categories = list(set(labels))
    result = []

    for label in labels:
        row = []

        for category in categories:
            if label == category:
                row.append(1.0)
            else:
                row.append(0.0)

        result.append(row)

    return np.array(result)


labels = ["cat", "dog", "bird", "cat"]
print(one_hot_encode(labels))
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [1. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
